# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(703, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Users/c7278pt/13.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(0, 160, 341, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.comboBox_hwType = QtWidgets.QComboBox(self.tab)
        self.comboBox_hwType.setGeometry(QtCore.QRect(0, 20, 241, 22))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.comboBox_hwType.setFont(font)
        self.comboBox_hwType.setObjectName("comboBox_hwType")
        self.comboBox_hwType.addItem("")
        self.comboBox_hwType.addItem("")
        self.comboBox_hwType.addItem("")
        self.comboBox_hwType.addItem("")
        self.comboBox_hwType.addItem("")
        self.BTN_Device = QtWidgets.QPushButton(self.tab)
        self.BTN_Device.setGeometry(QtCore.QRect(250, 20, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.BTN_Device.setFont(font)
        self.BTN_Device.setObjectName("BTN_Device")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(40, 70, 51, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 50, 191, 16))
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(100, 70, 51, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 70, 51, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.BTN_empty = QtWidgets.QPushButton(self.tab)
        self.BTN_empty.setGeometry(QtCore.QRect(270, 390, 75, 23))
        self.BTN_empty.setObjectName("BTN_empty")
        self.BTN_SetBitrate = QtWidgets.QPushButton(self.tab)
        self.BTN_SetBitrate.setGeometry(QtCore.QRect(250, 70, 91, 23))
        self.BTN_SetBitrate.setObjectName("BTN_SetBitrate")
        self.BTN_online = QtWidgets.QPushButton(self.tab)
        self.BTN_online.setGeometry(QtCore.QRect(40, 120, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.BTN_online.setFont(font)
        self.BTN_online.setObjectName("BTN_online")
        self.BTN_offline = QtWidgets.QPushButton(self.tab)
        self.BTN_offline.setGeometry(QtCore.QRect(140, 120, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.BTN_offline.setFont(font)
        self.BTN_offline.setObjectName("BTN_offline")
        self.BTN_send1 = QtWidgets.QPushButton(self.tab)
        self.BTN_send1.setGeometry(QtCore.QRect(0, 390, 121, 23))
        self.BTN_send1.setObjectName("BTN_send1")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(380, 70, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setCenterOnScroll(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Combo_10ms = QtWidgets.QComboBox(self.tab)
        self.Combo_10ms.setGeometry(QtCore.QRect(600, 70, 69, 22))
        self.Combo_10ms.setObjectName("Combo_10ms")
        self.Combo_10ms.addItem("")
        self.Combo_10ms.addItem("")
        self.Combo_10ms.addItem("")
        self.BTN_sendmsgs = QtWidgets.QPushButton(self.tab)
        self.BTN_sendmsgs.setGeometry(QtCore.QRect(600, 110, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.BTN_sendmsgs.setFont(font)
        self.BTN_sendmsgs.setObjectName("BTN_sendmsgs")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(240, 140, 101, 20))
        self.checkBox.setObjectName("checkBox")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(380, 10, 291, 51))
        self.listWidget.setAutoFillBackground(True)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setModelColumn(0)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.listDTC = QtWidgets.QListWidget(self.tab)
        self.listDTC.setGeometry(QtCore.QRect(380, 210, 291, 161))
        self.listDTC.setObjectName("listDTC")
        self.BTN_ReadDTC = QtWidgets.QPushButton(self.tab)
        self.BTN_ReadDTC.setGeometry(QtCore.QRect(380, 180, 75, 23))
        self.BTN_ReadDTC.setObjectName("BTN_ReadDTC")
        self.BTN_ClearDTC = QtWidgets.QPushButton(self.tab)
        self.BTN_ClearDTC.setGeometry(QtCore.QRect(590, 180, 75, 23))
        self.BTN_ClearDTC.setObjectName("BTN_ClearDTC")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.radioButton = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton.setGeometry(QtCore.QRect(460, 160, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.listWidget.itemDoubleClicked['QListWidgetItem*'].connect(self.tabWidget.repaint)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PyCAN_Kit_ver0p1"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.comboBox_hwType.setItemText(0, _translate("Form", "0-None"))
        self.comboBox_hwType.setItemText(1, _translate("Form", "1-Virtual Device"))
        self.comboBox_hwType.setItemText(2, _translate("Form", "55-VN1610"))
        self.comboBox_hwType.setItemText(3, _translate("Form", "57-VN1630"))
        self.comboBox_hwType.setItemText(4, _translate("Form", "59-VN1640"))
        self.BTN_Device.setText(_translate("Form", "Choose Device"))
        self.comboBox.setItemText(0, _translate("Form", "500k"))
        self.comboBox.setItemText(1, _translate("Form", "250k"))
        self.comboBox.setItemText(2, _translate("Form", "125k"))
        self.comboBox.setItemText(3, _translate("Form", "OFF"))
        self.label.setText(_translate("Form", "CAN1        CAN2        CAN3        CAN4    "))
        self.comboBox_2.setItemText(0, _translate("Form", "500k"))
        self.comboBox_2.setItemText(1, _translate("Form", "250k"))
        self.comboBox_2.setItemText(2, _translate("Form", "125k"))
        self.comboBox_2.setItemText(3, _translate("Form", "OFF"))
        self.comboBox_3.setItemText(0, _translate("Form", "500k"))
        self.comboBox_3.setItemText(1, _translate("Form", "250k"))
        self.comboBox_3.setItemText(2, _translate("Form", "125k"))
        self.comboBox_3.setItemText(3, _translate("Form", "OFF"))
        self.BTN_empty.setText(_translate("Form", "Empty Info"))
        self.BTN_SetBitrate.setText(_translate("Form", "Set Bitrate"))
        self.BTN_online.setText(_translate("Form", "ONLINE"))
        self.BTN_offline.setText(_translate("Form", "OFFLINE"))
        self.BTN_send1.setText(_translate("Form", "Send 1 Msg test"))
        self.plainTextEdit.setPlainText(_translate("Form", "18DA10F1 03 22 01 9E 00 00 00 00\n"
"18DA10F1 03 22 01 8D 00 00 00 00"))
        self.Combo_10ms.setItemText(0, _translate("Form", "10ms"))
        self.Combo_10ms.setItemText(1, _translate("Form", "100ms"))
        self.Combo_10ms.setItemText(2, _translate("Form", "1000ms"))
        self.BTN_sendmsgs.setText(_translate("Form", "SEND"))
        self.checkBox.setText(_translate("Form", "Only show 29Bits"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "001-Unlock SGW"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "002-Clear PCM DTC"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "003-TBD..."))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.BTN_ReadDTC.setText(_translate("Form", "Read DTC"))
        self.BTN_ClearDTC.setText(_translate("Form", "Clear DTC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Normal"))
        self.radioButton.setText(_translate("Form", "RadioButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
